name: Lambda Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.3.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Imports
        env:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
        run: ./resources-import.sh
        continue-on-error: true

      - name: Terraform Plan
        env:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
        run: |
          terraform plan \
          -var="aws_account_id=${AWS_ACCOUNT_ID}" \
          -out=tfplan

      - name: Terraform Apply
        run: terraform apply "tfplan"

      - name: Setup Python
        uses: actions/setup-python@v5

      - name: Install AWS SAM CLI
        uses: aws-actions/setup-sam@v2

      # - name: Build and Deploy
      #   run: |
      #     sam build --use-container
      #     sam deploy --no-confirm-changeset --no-fail-on-empty-changeset
